// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"t3hj182zx0","name":"ThingTableCRUD","description":"","endpoint":"https://t3hj182zx0.execute-api.ap-southeast-1.amazonaws.com/Development","region":"ap-southeast-1","paths":["/ThingTable","/ThingTable/123"]},{"id":"m26txigc8l","name":"WearerTableCRUD","description":"","endpoint":"https://m26txigc8l.execute-api.ap-southeast-1.amazonaws.com/Development","region":"ap-southeast-1","paths":["/WearerTable","/WearerTable/123"]},{"id":"fcxhmrkllj","name":"WatchTableCRUD","description":"","endpoint":"https://fcxhmrkllj.execute-api.ap-southeast-1.amazonaws.com/Development","region":"ap-southeast-1","paths":["/WatchTable","/WatchTable/123"]}],
    'aws_cognito_identity_pool_id': 'ap-southeast-1:7b57b441-8de2-465e-ad49-b10c6732bdaf',
    'aws_cognito_region': 'ap-southeast-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'reactnativeeldercare-hosting-mobilehub-64077983',
    'aws_content_delivery_bucket_region': 'ap-southeast-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3vcunb5aumbnz.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'ap-southeast-1',
    'aws_dynamodb_table_schemas': [{"tableName":"reactnativeeldercare-mobilehub-64077983-WatchTable","attributes":[{"name":"userId","type":"S"},{"name":"WearerId","type":"S"},{"name":"Nickname","type":"S"}],"indexes":[],"region":"ap-southeast-1","hashKey":"userId","rangeKey":"WearerId"},{"tableName":"reactnativeeldercare-mobilehub-64077983-ThingTable","attributes":[{"name":"userId","type":"S"},{"name":"WearerId","type":"S"}],"indexes":[],"region":"ap-southeast-1","hashKey":"userId"},{"tableName":"reactnativeeldercare-mobilehub-64077983-WearerTable","attributes":[{"name":"userId","type":"S"},{"name":"Gender","type":"S"},{"name":"Lastname","type":"S"},{"name":"Name","type":"S"}],"indexes":[],"region":"ap-southeast-1","hashKey":"userId"}],
    'aws_project_id': 'bfc546f3-8b74-4662-a1f7-4720e4e07a89',
    'aws_project_name': 'React-Native-Eldercare',
    'aws_project_region': 'ap-southeast-1',
    'aws_resource_bucket_name': 'reactnativeeldercare-deployments-mobilehub-64077983',
    'aws_resource_name_prefix': 'reactnativeeldercare-mobilehub-64077983',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'reactnativeeldercare-userfiles-mobilehub-64077983',
    'aws_user_files_s3_bucket_region': 'ap-southeast-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-southeast-1_Efn1fiJS7',
    'aws_user_pools_web_client_id': '50qp35f6229lj2c1i7d9lede4m',
}

export default awsmobile;
