// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"3hni2ofd86","name":"ThingTableCRUD","description":"","endpoint":"https://3hni2ofd86.execute-api.ap-southeast-1.amazonaws.com/Development","region":"ap-southeast-1","paths":["/ThingTable","/ThingTable/123"]},{"id":"dlu9epmwy6","name":"WearerTableCRUD","description":"","endpoint":"https://dlu9epmwy6.execute-api.ap-southeast-1.amazonaws.com/Development","region":"ap-southeast-1","paths":["/WearerTable","/WearerTable/123"]},{"id":"2fvpuvbvuj","name":"WatchTableCRUD","description":"","endpoint":"https://2fvpuvbvuj.execute-api.ap-southeast-1.amazonaws.com/Development","region":"ap-southeast-1","paths":["/WatchTable","/WatchTable/123"]}],
    'aws_cognito_identity_pool_id': 'ap-southeast-1:7716aad6-ec79-4334-b1e9-d45aedfe1082',
    'aws_cognito_region': 'ap-southeast-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'eldercarebackendv-hosting-mobilehub-797506409',
    'aws_content_delivery_bucket_region': 'ap-southeast-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1k5evw07mmoc9.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'ap-southeast-1',
    'aws_dynamodb_table_schemas': [{"tableName":"eldercarebackendv-mobilehub-797506409-WearerTable","attributes":[{"name":"WearerId","type":"S"},{"name":"DeviceId","type":"S"},{"name":"Name","type":"S"},{"name":"gender","type":"S"},{"name":"lastname","type":"S"}],"indexes":[],"region":"ap-southeast-1","hashKey":"WearerId","rangeKey":"DeviceId"},{"tableName":"eldercarebackendv-mobilehub-797506409-ThingTable","attributes":[{"name":"ThingId","type":"S"},{"name":"WearerId","type":"S"}],"indexes":[],"region":"ap-southeast-1","hashKey":"ThingId","rangeKey":"WearerId"},{"tableName":"eldercarebackendv-mobilehub-797506409-WatchTable","attributes":[{"name":"userId","type":"S"},{"name":"WearerId","type":"S"}],"indexes":[],"region":"ap-southeast-1","hashKey":"userId","rangeKey":"WearerId"}],
    'aws_project_id': 'f91452a8-9167-4877-80df-b367b09c1995',
    'aws_project_name': 'ElderCareBackend V.2',
    'aws_project_region': 'ap-southeast-1',
    'aws_resource_bucket_name': 'eldercarebackendv-deployments-mobilehub-797506409',
    'aws_resource_name_prefix': 'eldercarebackendv-mobilehub-797506409',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'eldercarebackendv-userfiles-mobilehub-797506409',
    'aws_user_files_s3_bucket_region': 'ap-southeast-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-southeast-1_Efn1fiJS7',
    'aws_user_pools_web_client_id': 'nhqvvqk1oucn0qflhtecieia7',
}

export default awsmobile;
